print("Hello Python")
print("This update from commit 1")
print("This is second update from commit 1")
print("This is third commit from commit 1")
print("This is fourth commit from commit 1")
print("This is first commit from commit2")
print("This is 2nd commit from commit 2")
print("This is 3nd commit from commit 2")
